{
  "status": 500,
  "error": "INTERNAL_SERVER_ERROR",
  "message": "An unexpected error occurred",
  "details": "Please try again later or contact support if the problem persists",
  "path": "/auth/signup",
  "timestamp": "2025-09-13 23:23:29",
  "fieldErrors": null,
  "metadata": null
}