{
  "status": 500,
  "error": "INTERNAL_SERVER_ERROR",
  "message": "An unexpected error occurred",
  "details": "Please try again later or contact support if the problem persists",
  "path": "/api/patients/223e4567-e89b-12d3-a456-426614174014",
  "timestamp": "2025-09-07 16:52:46",
  "fieldErrors": null,
  "metadata": null
}